### ISSUE TITLE
Bug id 1 -The buttons that redirect to "the-blog-piece" redirect to a broken link.

### ISSUE THREAD

**Issue by VictorCespedesCC** [victor-villca/nextjs-website-app#4]
Severity
Medium

Description
When you click on the button that goes to "the-blog-piece", a new page opens but it shows a 404 error.

Requirements
-internet connection
-available web browser (latest version of chrome)
-access the page https://blog-piece.vercel.app/

Steps
-go to https://blog-piece.vercel.app/
-scroll down to the bottom of the main page
-At the bottom left you will find two circular buttons that redirect to external pages. Press the button with the globe icon
-check the redirection to "the-blog-piece" page.

Espected result
The buttons redirect to a page that works correctly.

Actual result
The buttons redirect to a broken page. The error that is displayed is "404: NOT_FOUND"

Status
Open

**Comment by victor-villca** [comment]
Thanks for the bug, I will check it and fix it.
